### ISSUE TITLE
Column documentsReferenced is removed, intentionally?

### ISSUE THREAD

**Issue by neofob** [dod-advana/gamechanger-web#602]
Should the script(?) [`2022103116520573-v5-new-responsiblity-data.js`][1] run at the very last?
Should it run at the beginning as in the order of `vNUMBER`? If so, the filename format should be consistent: `CONSTANT_STRING_LENGTH-vNUMBER-Blah...js`, ja?

It removes the column `documentsReferenced`. Is that intentional as the end result?

This is after running `step_1`:
```
game_changer=# select * from responsibilities;
 id | filename | documentTitle | responsibilityText | status | organizationPersonnelNumbering | organizationPersonnelText | organizationPersonnelEntities | responsibilityNumbering | responsibilityEntities 
----+----------+---------------+--------------------+--------+--------------------------------+---------------------------+-------------------------------+-------------------------+------------------------
(0 rows)

```

Snippet from ./start.sh run in `gamechanger-web`:
```
== 2022032214385620-v113-create-doc-ingest-request.js: migrating =======
== 2022032214385620-v113-create-doc-ingest-request.js: migrated (0.021s)

== 20220510223219-v117-update-clone-meta-add-header: migrating =======
== 20220510223219-v117-update-clone-meta-add-header: migrated (0.024s)

== 2022103116520573-v5-new-responsiblity-data: migrating =======
== 2022103116520573-v5-new-responsiblity-data: migrated (0.036s)

== 2023022214020000-v134-create-policy-search-performance-tests: migrating =======
== 2023022214020000-v134-create-policy-search-performance-tests: migrated (0.021s)
```

If that is intended result, then the [insertion(s)][0] to populate `responsibilities` table would not work as it lacks the column `documentsReferenced`.

References:
* https://github.com/dod-advana/gamechanger-web/commit/cf28ac8b82855a6ae25f0919550bb2d7ad4c4779
* https://github.com/neofob/gamechanger-web/blob/tp-dev/backend/node_app/init/gc-psql-init.sql#L176-L278

CC: @drospond

[1]: https://github.com/dod-advana/gamechanger-web/commit/cf28ac8b82855a6ae25f0919550bb2d7ad4c4779
[0]: https://github.com/neofob/gamechanger-web/blob/tp-dev/backend/node_app/init/gc-psql-init.sql#L176-L278

**Comment by drospond** [comment]
The schema is outdated for the insert sql script referenced. Those migrations were intentional. We can remove the reference to the insert script in the gamechanger repo. We may add a sample data insert script with the updated schema in the future. I will add it to our backlog.
